# Generated by Django 2.2.24 on 2022-05-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0006_remove_data_counrty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='volume',
            field=models.FloatField(),
        ),
    ]
